# Generated by Django 4.1.2 on 2022-11-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_amenity_created_at_amenity_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="name",
            field=models.CharField(default="", max_length=180),
        ),
        migrations.AlterField(
            model_name="amenity",
            name="description",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="city",
            field=models.CharField(default="Seoul", max_length=80),
        ),
        migrations.AlterField(
            model_name="room",
            name="country",
            field=models.CharField(default="South Korea", max_length=50),
        ),
    ]
